services:
  redis:
    image: redis:7
    container_name: leads-redis
    restart: unless-stopped
    ports:
      - "6379:6379"    # Redis default port
    networks:
      - monitoring-net
  postgres:
    image: postgres:16
    container_name: license-postgres
    environment:
      POSTGRES_DB: license
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - license_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - monitoring-net

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  license_postgres_data:
  pgadmin_data:

networks:
  monitoring-net:
    driver: bridge