server:
  port: 8080

spring:
  application:
    name: leads-gateway-service

  cloud:
    gateway:
      routes:
        # User Service Route
        - id: app1-route
          uri: lb://app-1   # must match Eureka serviceId
          predicates:
            - Path=/api/users/**

        # Order Service Route
        - id: app2-route
          uri: lb://app-2
          predicates:
            - Path=/api/orders/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # still handy for debugging

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
