server:
  port: 8080

spring:
  application:
    name: leads-gateway-service
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: api-gateway-license-consumer
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  cloud:
    gateway:
      routes:
        # User Service Route
        - id: user-service
          uri: lb://userservice   # must match Eureka serviceId
          predicates:
            - Path=/api/users/**
          filters:
            - name: RateLimitFilter

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # still handy for debugging

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  kafka:
    topic:
      client-license: client-license-events
