events {}

http {

log_format upstreamlog '$remote_addr - $host '
                       'upstream: $upstream_addr '
                       'status: $status';

access_log /var/log/nginx/access.log upstreamlog;

    upstream gateway_cluster {
        server api-gateway:8080;
    }

    upstream frontend_cluster {
        server frontend:80;
    }

    server {
        listen 80;

        # React frontend
        location / {
            proxy_pass http://frontend_cluster;
            proxy_set_header Host $host;
        }

        # API Gateway
        location /api/ {
            proxy_pass http://gateway_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
